### ISSUE TITLE
Continued "Failed to find devicetree fragment"

### ISSUE THREAD

**Issue by sinqbad** [jadonk/bonescript#132]
I am getting the same issue as [issue 78
](https://github.com/jadonk/bonescript/issues/74) and [issue 84](https://github.com/zettajs/zetta/issues/84) that is while trying to run `var b = require('bonescript')
var led1 = "USR3";
var led2 = "P8_8";

b.pinMode(led1, b.OUTPUT);
b.pinMode(led2, b.OUTPUT);

var state = b.LOW;
b.digitalWrite(led1, state);
b.ditigalWrite(led2, state);
setInterval(toggle, 1000);

function toggle()
{
    if(state == b.LOW) state = b.HIGH;
    else state = b.LOW;
    b.digitalWrite(led1, state);
    b.digitalWrite(led2, state);
}`

I get the error `error: Failed to find devicetree fragment: bspm_P8_13_f
info:  0: 54:PF--- 
 1: 55:PF--- 
 2: 56:PF--- 
 3: 57:PF--- 
 4: ff:P-O-L Bone-LT-eMMC-2G,00A0,Texas Instrument,BB-BONE-EMMC-2G
 5: ff:P-O-L Bone-Black-HDMI,00A0,Texas Instrument,BB-BONELT-HDMI
`
Running 'TERM=none npm install -g bonescript' to reinstall bonescript gets me 'npm http GET https://registry.npmjs.org/bonescript
npm http GET https://registry.npmjs.org/bonescript
npm http GET https://registry.npmjs.org/bonescript
npm ERR! Error: CERT_NOT_YET_VALID
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.8.13-bone47
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bonescript"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0'

So it's not reinstalling. How can I fix this?

**Comment by sinqbad** [comment]
TERM=none npm install -g bonescript worked eventually. problem solved.
